### ISSUE TITLE
More examples in the README, please :)

### ISSUE THREAD

**Issue by sethladd** [gmosx/dart-inflection#1]
First off, super cool! Thanks for contributing this library.

I wasn't sure what the inflector was. If you have time, more examples in the README would help explain what this is.

Also, while you're in there, maybe include a note on how to file issues.

Cheers!

**Comment by gmosx** [comment]
Sure, I will update the README tonight... Will also add some more of the
missing functionality.

On Sun, Feb 1, 2015 at 6:13 PM, Seth Ladd notifications@github.com wrote:

> First off, super cool! Thanks for contributing this library.
> 
> I wasn't sure what the inflector was. If you have time, more examples in
> the README would help explain what this is.
> 
> Also, while you're in there, maybe include a note on how to file issues.
> 
> Cheers!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gmosx/dart-inflection/issues/1.

## 

http://www.gmosx.com

**Comment by gmosx** [comment]
OK, I updated the example taking your suggestions into account. Moreover, I re-factored the code and added plural/singular inflections. If you have any further comments (especially how to make the API more Dart-like) let me  know.
