### ISSUE TITLE
Suggestions (take 'em or leave 'em :)

### ISSUE THREAD

**Issue by sethladd** [gmosx/dart-inflection#2]
Could we add a CHANGELOG.md ?

Four comments for the library-level variables like PLURAL.

1) use a type annotation:

`final Converter<String, String> Plural = new PluralEncoder._()`

2) use camel case instead of all caps for the name

3) use a library-private constructor.

4) consider a const constructor, which is really nice for this case

Optional:

5) Consider making these classes callable, so you can do:

`Pluralize('input')` as an alternative to `Pluralize.convert('input')`

To do so, add a `String call(String input)` method to your converters.

Cheers!

**Comment by gmosx** [comment]
There is a CHANGELOG already. Re your other suggestions, I will have a go at them, thanks.

**Comment by gmosx** [comment]
Implemented most of them. Can't make the Plural/Singular encoders const as they can be customized by clients with extra rules. Moreover, I added some 'shortcut' functions instead of making the Encoders callable.

**Comment by sethladd** [comment]
+1 for the shortcut functions, thanks!
