### ISSUE TITLE
Continuous integration system?

### ISSUE THREAD

**Issue by devoncarew** [gmosx/dart-inflection#4]
Have you thought about hooking this up to a CI system (drone / travis)? It makes it pretty easy to get tests running on each PR.

**Comment by gmosx** [comment]
Hmm, never used a CI system, I guess I can give it a go. Which one do you suggest?

**Comment by devoncarew** [comment]
Travis-ci.org is a bit more featureful now, and recently got first class dart support. I'm happy to send a PR to get it going; you'd need to finish it up to tell travis about your repo.

**Comment by gmosx** [comment]
OK, please send me the PR and I will handle the rest...

**Comment by devoncarew** [comment]
A green build :)

https://travis-ci.org/gmosx/dart-inflection/builds

**Comment by gmosx** [comment]
Travis looks cool ;-)
